from pathlib import Path

D = "</div>"
M = "</motion.div>"

content = (
"'use client'\n\n"
"import { motion, AnimatePresence } from 'framer-motion'\n"
"import { Brain, Zap } from 'lucide-react'\n"
"import { cn } from '@/lib/utils'\n"
"import type { AIInsight } from '@/lib/insight-types'\n"
"import { InsightSeverityBadge } from './insight-severity-badge'\n"
"import { InsightConfidenceMeter } from './insight-confidence-meter'\n"
"import { categoryMeta } from './insight-config'\n\n"
"interface InsightDetailPanelProps {\n"
"  insight: AIInsight | null\n"
"  className?: string\n"
"}\n\n"
"export function InsightDetailPanel({ insight, className }: InsightDetailPanelProps) {\n"
"  return (\n"
"    <motion.div className={cn('glass-card sticky top-24 rounded-xl border border-border/50 p-6', className)}>\n"
"      <h2 className=\"mb-4 text-lg font-semibold\">Insight Analysis</h2>\n"
"      <AnimatePresence mode=\"wait\">\n"
"        {insight ? (\n"
"          <motion.div\n"
"            key={insight.id}\n"
"            initial={{ opacity: 0, y: 12 }}\n"
"            animate={{ opacity: 1, y: 0 }}\n"
"            exit={{ opacity: 0, y: -8 }}\n"
"            className=\"space-y-5\"\n"
"          >\n"
"            <div className=\"flex flex-wrap items-center gap-2\">\n"
"              <InsightSeverityBadge severity={insight.severity} />\n"
"              <span className=\"rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground\">\n"
"                {categoryMeta[insight.category].label}\n"
"              </span>\n"
f"            {D}\n"
"            <div>\n"
"              <h3 className=\"text-lg font-semibold leading-tight\">{insight.title}</h3>\n"
"              <p className=\"mt-1 text-xs text-muted-foreground\">{insight.timestamp}</p>\n"
f"            {D}\n"
"            <div>\n"
"              <p className=\"mb-1 text-xs font-medium uppercase tracking-wider text-muted-foreground\">Explanation</p>\n"
"              <p className=\"text-sm leading-relaxed text-foreground/90\">{insight.explanation || insight.description}</p>\n"
f"            {D}\n"
"            <div className=\"rounded-lg border border-primary/20 bg-primary/5 p-4\">\n"
"              <div className=\"mb-2 flex items-center gap-2 text-primary\">\n"
"                <Zap className=\"h-4 w-4\" />\n"
"                <span className=\"text-xs font-semibold uppercase tracking-wider\">Recommendation</span>\n"
f"              {D}\n"
"              <p className=\"text-sm leading-relaxed\">{insight.recommendation}</p>\n"
"              <p className=\"mt-2 text-xs text-muted-foreground\">Action: {insight.suggestedAction}</p>\n"
f"            {D}\n"
"            <InsightConfidenceMeter value={insight.confidence} />\n"
"            <div className=\"flex gap-2 pt-2\">\n"
"              <motion.button type=\"button\" whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} className=\"flex-1 rounded-lg bg-primary py-2.5 text-sm font-medium text-primary-foreground\">Apply</motion.button>\n"
"              <motion.button type=\"button\" whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} className=\"rounded-lg border border-border px-4 py-2.5 text-sm font-medium\">Dismiss</motion.button>\n"
f"            {D}\n"
f"          {M}\n"
"        ) : (\n"
"          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className=\"flex h-64 flex-col items-center justify-center text-center\">\n"
"            <Brain className=\"mb-3 h-12 w-12 text-muted-foreground/25\" />\n"
"            <p className=\"text-sm text-muted-foreground\">Select an insight to view full analysis</p>\n"
f"          {M}\n"
"        )}\n"
"      </AnimatePresence>\n"
f"    {M}\n"
"  )\n"
"}\n"
)

Path("components/insights/insight-detail-panel.tsx").write_text(content, encoding="utf-8")
print("ok")
